apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-hello
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-1/quarkus-hello@sha256:c10e31d17a8b59edfd35d1d8b73b8877bf4327905980758e5a6d5b25e39ac42c
        name: my-java-quarkus
        resources: {}
status: {}
