apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-hello
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-hello
    app.kubernetes.io/part-of: rhtap-buildpack-demo-1
  name: quarkus-hellop7fs
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: quarkus-hello
    weight: null
status: {}
